# Generated by Django 5.2.4 on 2025-08-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_admin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=12)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('course', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('session', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('pic', models.FileField(max_length=155, upload_to='student')),
                ('regdate', models.DateField(auto_now_add=True, max_length=30)),
            ],
        ),
    ]
