# Generated by Django 5.2.4 on 2025-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_course_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
                ('session', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('file', models.FileField(max_length=255, upload_to='sthyudy')),
            ],
        ),
    ]
